#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(k, n):
    x = range(1, len(n))
    for i in x:
        # print(n[i])
        immidiet = n[i]
        while i > 0:
            if n[i-1] > immidiet:

                n[i] = n[i-1]
                print(*n)
                n[i-1] = immidiet

            i -= 1
    print(*n)
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
